name: Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install uv and enable caching
        uses: astral-sh/setup-uv@v6 # Use the official uv setup action
        with:
          python-version: 3.11 # Ensure this matches your setup-python version
          enable-cache: true  # This enables uv's internal cache with GitHub Actions caching

      - name: Install documentation dependencies
        run: make docs-install

      - name: Deploy documentation to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          make docs-publish
